// Fun audit runner: `npm run fun:audit`. Measures every campaign and Physics Lab level with
// src/analysis/funAudit.ts and writes docs/fun/fun-audit.md (readable) and fun-audit.json (data).
// FUN_SAMPLES sets samples per measurement (default 12) and FUN_SEED the random seed; FUN_ONLY=id,id limits the levels and
// writes docs/fun/fun-audit.partial.md instead.

import { mkdirSync, writeFileSync } from 'node:fs';
import { it } from 'vitest';
import '../../src/components';
import { auditLevel, LIMITS, SPREADS, type FunReport } from '../../src/analysis/funAudit';
import { CAMPAIGN, CHAPTERS, levelCode } from '../../src/game/campaign';
import { LAB } from '../../src/game/levels/lab';

const samples = Number(process.env.FUN_SAMPLES ?? 12);
const seed = Number(process.env.FUN_SEED ?? 7);
const only = process.env.FUN_ONLY?.split(',');

it('audits every level', () => {
  const entries = [
    ...CAMPAIGN.map((e, i) => ({ e, code: levelCode(i), group: CHAPTERS.find((c) => c.index === e.chapter)?.title ?? '' })),
    ...LAB.map((e, i) => ({ e, code: `L${i + 1}`, group: 'Physics Lab' })),
  ].filter((x) => !only || only.includes(x.e.level.id));

  const seen = new Set<string>();
  const rows: (FunReport & { code: string; group: string })[] = [];
  for (const { e, code, group } of entries) {
    const r = auditLevel(e.level, e.solutions[0], { samples, seed });
    const kinds = new Set([...e.level.inventory.map((i) => i.type), ...e.level.startingObjects.map((o) => o.type), ...e.level.fixedObjects.map((o) => o.type)]);
    kinds.delete('wall');
    if (group !== 'Physics Lab') {
      r.newParts = [...kinds].filter((k) => !seen.has(k));
      for (const k of kinds) seen.add(k);
    }
    rows.push({ ...r, code, group });
  }

  mkdirSync('docs/fun', { recursive: true });
  // A partial run (FUN_ONLY) leaves the committed full report alone.
  const base = only ? 'docs/fun/fun-audit.partial' : 'docs/fun/fun-audit';
  writeFileSync(`${base}.json`, JSON.stringify({ samples, spreads: SPREADS, limits: LIMITS, levels: rows }, null, 1) + '\n');
  writeFileSync(`${base}.md`, render(rows));
}, 3_600_000);

const f1 = (x: number) => x.toFixed(1);
const pct = (x: number) => `${Math.round(x * 100)}%`;

const render = (rows: (FunReport & { code: string; group: string })[]) => {
  const out: string[] = [];
  out.push('# Fun audit', '');
  out.push(`Generated by \`npm run fun:audit\` (${samples} samples per measurement). What each column means and why the thresholds are where they are: [MEASURING_FUN.md](MEASURING_FUN.md).`, '');
  const flagged = rows.filter((r) => r.flags.length);
  const byFlag = new Map<string, number>();
  for (const r of rows) for (const f of r.flags) byFlag.set(f.split(':')[0], (byFlag.get(f.split(':')[0]) ?? 0) + 1);
  out.push('## Summary', '');
  out.push(`- ${rows.length} levels measured, median score ${median(rows.map((r) => r.score))}, ${flagged.length} with at least one flag.`);
  for (const [k, n] of [...byFlag].sort((a, b) => b[1] - a[1])) out.push(`- ${k}: ${n} level${n === 1 ? '' : 's'}`);
  out.push('');
  out.push('## Lowest scores', '');
  for (const r of [...rows].sort((a, b) => a.score - b.score).slice(0, 10)) out.push(`- **${r.code} ${r.name}** (${r.score}): ${r.flags.join('; ') || 'no flags'}`);
  out.push('');
  let group = '';
  for (const r of rows) {
    if (r.group !== group) {
      if (group) out.push('');
      group = r.group;
      out.push(`## ${group}`, '');
      out.push('| Level | Score | Parts | Stages | Domains | Solve s | First s | Lull s | Player share | Together ±6/±12 | Tolerance | Near miss | New parts | Flags |');
      out.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|');
    }
    const tol = r.perPart.length ? `±${r.tolerance}px${r.fiddliest ? ` (${r.fiddliest})` : ''}` : 'n/a';
    out.push(
      `| ${r.code} ${r.name} | ${r.score} | ${r.partsPlaced} | ${r.stages} | ${r.domains.length} | ${f1(r.solveTime)} | ${f1(r.firstStageAt)} | ${f1(r.longestLull)} | ${pct(r.playerShare)} | ${r.forgiveness.map((t) => pct(t.rate)).join(' / ')} | ${tol} | ${pct(r.nearMiss)} | ${r.newParts.join(', ')} | ${r.flags.join('; ')} |`,
    );
  }
  out.push('');
  return out.join('\n');
};

const median = (xs: number[]) => {
  const s = [...xs].sort((a, b) => a - b);
  return s.length ? s[Math.floor(s.length / 2)] : 0;
};
